# Default values for allo-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/skiscontent/allo-k8s
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "89727f67a222e8a300661153984068ccfea805a1"
  # specify the image digest to use
  digest: "sha256:cb65ef422ad22d3da7db73ee4982a80afffad977f108b2e30d38ab06213fb629"
imagePullSecrets:
  - name: "ghcr-regcred"
nameOverride: ""
fullnameOverride: ""
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "allo.a-sk.com"
  hosts:
    - host: allo.a-sk.com
      paths:
        - path: /
          pathType: ImplementationSpecific
          servicePort: 80
  tls:
    - secretName: allo-tls
      hosts:
        - allo.a-sk.com
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext:
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - allo-k8s
          topologyKey: kubernetes.io/hostname
