apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: "1.14.3"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: aws
    policy: sync
    registry: txt
    txtOwnerId: "allo-k8s"
    domainFilters:
      - a-sk.com
    aws:
      region: us-east-1
      zoneType: public
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi 