apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: allo-k8s-development
spec:
  destination:
    namespace: allo-k8s-development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/allo-k8s
    repoURL: https://github.com/skiscontent/allo-k8s.git
    targetRevision: asltw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
