project: production
source:
  repoURL: 'https://github.com/skiscontent/allo-k8s.git'
  path: helm
  targetRevision: main
destination:
  server: 'https://kubernetes.default.svc'
  namespace: allo-k8s-production
syncPolicy:
  automated: {}
info:
  - name: foo
    value: This is some information for production
