on:
  push:
    paths-ignore:
      - "helm/**"
      - "argocd/**"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run the tests
    env: 
      PYTHON_VERSION: '3.11'
      PYTHON_VERSION_RUFF: 'py311'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.9.9  pytest==8.3.5
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint and with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check --output-format=github --select=E9,F63,F7,F82 --target-version=${{ env.PYTHON_VERSION_RUFF }} .
      - name: Test with pytest
        run: |
          python -m pytest

  allo_k8s_job:
    needs: tests
    runs-on: ubuntu-latest
    name: This job creates a Docker image
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bandit Action
        uses: mdegis/bandit-action@v1.0
        id: bandit
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "allo"
          level: high
          confidence: high
          exit_zero: true
      - name: Repo name lowercase
        id: convertRepository
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_NAME }}
      - id: echoRegistryName
        run: echo ${{ steps.convertRepository.outputs.lowercase }}
      - name: Log into registry ${{ steps.convertRepository.outputs.lowercase }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CLASSIC_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ steps.convertRepository.outputs.lowercase }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Update Image Version
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: >-
            yq eval '.image.repository = "${{ env.REGISTRY }}/${{ steps.convertRepository.outputs.lowercase }}" |
            .image.tag = "${{ github.sha }}" |
            .image.digest = "${{ steps.build-and-push.outputs.digest }}"'
            -i helm/allo-k8s/values.yaml
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply image name changes